apiVersion: v1
kind: Service
metadata:
  name: wsrestauditoriaapi
  namespace: dev
spec:
  ports:
    - name: http
      port: 18082
    - name: https
      port: 443
  type: LoadBalancer    
  selector:
    app: wsrestauditoriaapi