spring:
  application:
    name: wsRestAuditoriaAPI
server:
  port: 18082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://SBBOGLAPPROJO7.sophos.col.com:8761/eureka}
  instance:
    preferIpAddress: true
    status-page-url-path: /v2/api-docs/
    health-check-url-path: /api/actividad/health
    virtual-host-name: SBBOGLAPPROJO7
    metadata-map:
      app-owner: Sophos Solutions
      description: Servicio que expone funcionalidades de Auditoria